name: pc-on

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Terminal Services 
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
      shell: powershell

    - name: Enable Remote Desktop in Firewall
      run: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: powershell

    - name: Enable RDP User Authentication
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      shell: powershell

    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password
      shell: powershell

    - name: creat ssh tunnel
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -R serveo.net:3389:localhost:3389 serveo.net
