name: pc
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Enable Firewall for Remote Desktop
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set Password for runneradmin
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Clone Repository
      run: git clone https://github.com/MrBY510KONFACEBOOK/watchpro.git

    - name: Download Playit.gg Installer
      run: Invoke-WebRequest https://github.com/MrBY510KONFACEBOOK/watchpro/releases/download/latest/playit-windows-x86_64-signed.msi -OutFile watchpro/playit-windows-x86_64-signed.msi

    - name: Install Playit.gg
      run: |
        # Navigate to the directory where the MSI is located
        cd watchpro
        # Install the MSI silently
        Start-Process msiexec.exe -ArgumentList '/i playit-windows-x86_64-signed.msi /quiet' -Wait

    - name: List and Run Applications in Playit Directory
      run: |
        # List all applications in the directory
        Get-ChildItem 'C:\Program Files (x86)\Playit\' -Filter '*.exe' | ForEach-Object { Start-Process $_.FullName -NoNewWindow }
