name: pc-on

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Terminal Services 
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
      shell: powershell

    - name: Enable Remote Desktop in Firewall
      run: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: powershell

    - name: Enable RDP User Authentication
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      shell: powershell

    - name: Set User Password
      run: |
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password
      shell: powershell

    - name: Download Playit.gg Client
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-windows-x86_64-signed.msi" -OutFile "$env:TEMP\playit.msi"
      shell: powershell

    - name: Install Playit.gg Client
      run: |
        Start-Process -FilePath "$env:TEMP\playit.msi" -ArgumentList "/quiet" -Wait
      shell: powershell

    - name: Run Python HTTP Server
      run: |
        python -m http.server 8080 > NUL 2>&1 &
      shell: bash

    - name: Set up localhost.run Tunnel
      run: |
        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -R 80:localhost:8080 nokey@localhost.run.run
      shell: bash
