name: pcon
on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Trigger manually

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable Terminal Services
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - name: Enable Firewall for Remote Desktop
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Enable User Authentication
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Set Password for runneradmin
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Clone Repository
        run: git clone https://github.com/MrBY510KONFACEBOOK/watchpro.git

      - name: Install Chocolatey (if not already installed)
        run: |
          if (-Not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          }

      - name: Install Ngrok via Chocolatey
        run: choco install -y ngrok

      - name: Configure Ngrok Authtoken
        run: ngrok config add-authtoken 2eg1KXlEo9QtqqmlMEjzvvffedG_3M2dZvACkZiuWvEaZ37wJ

      - name: Expose Ngrok TCP Tunnel on Port 3389
        run: ngrok tcp 3389 > /dev/null &

      - name: Wait for Ngrok to Initialize
        run: Start-Sleep -Seconds 3  # Wait for Ngrok to initialize


      - name: Timer Until Next Run
        run: |
          echo "Waiting until the next scheduled run..."
          Start-Sleep -Seconds 86400  # Wait for 24 hours (86400 seconds) until the next run
