name: FTP Server Deployment

on: 
  push:
    branches:
      - main

jobs:
  deploy-ftp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run FTP Server Container
      run: |
        docker run \
          --detach \
          --env FTP_PASS=1K \
          --env FTP_USER=mollehya \
          --name my-ftp-server \
          --publish 20-21:20-21/tcp \
          --publish 40000-40009:40000-40009/tcp \
          --volume /storage:/home/mollehya \
          garethflowers/ftp-server
    
    - name: Set up Serveo.net SSH Tunnel
      run: |
        ssh -o "StrictHostKeyChecking=no" -R 0:localhost:21 serveo.net
