name: Enable SSH Server

on: [push]

jobs:
  enable-ssh-server:
    runs-on: windows-latest

    steps:
    - name: Install OpenSSH Server
      run: |
        Add-WindowsFeature -Name OpenSSH-Server

    - name: Start SSH Server
      run: |
        Start-Service sshd
        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -R 0:localhost:22 serveo.net