name: Install OpenSSH

on:
  push:
    branches:
      - main

jobs:
  install-openssh:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenSSH
      uses: microsoft/windows-openSSH-install@v1

    - name: Start OpenSSH service
      uses: microsoft/windows-tools@v1
      with:
        tool: 'powershell'
        script: |
          Start-Service sshd

    - name: Check OpenSSH service status
      uses: microsoft/windows-tools@v1
      with:
        tool: 'powershell'
        script: |
          Get-Service sshd

    - name: Check OpenSSH version
      uses: microsoft/windows-tools@v1
      with:
        tool: 'powershell'
        script: |
          ssh -V