name: Download and Upload Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and Extract file
      run: |
        wget https://download944.mediafire.com/qjx0dqjo5ywg1s-ouGSwOPR3k1Jvpi8kmlQDJCl1eAKKCEYfV8dKC5AOike1aaKJN3Gajk94qwMuc570m8qzkwEgfEgbgc49qnvjpjC0fdNx6rpSEUUfnwIUWh9bu7Y2dbwniZ2Ajg9ScRoQnWCXT4pq92Fcdev40TIpz7Nwen5SQw/1j9thc1mixgm2di/JITOSSA-master.7z
        7z x JITOSSA-master.7z

    - name: Upload extracted file
      uses: actions/upload-artifact@v2
      with:
        name: extracted-files
        path: JITOSSA-master
