name: Stream Video

on:
  push:
    branches:
      - main

jobs:
  stream_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Stream video
      run: |
        sudo apt install ffmpeg -y
        chmod +x s.sh
        ./s.sh "https://rr3---sn-p5qlsnrr.googlevideo.com/videoplayback?expire=1715124983&ei=l2Y6ZqXOJtmykucP4cC-2Ac&ip=102.129.235.171&id=o-ACT8fi8dA6C4TC52uCtIi-ADLxNREFV80xuuzwuWXbfz&itag=22&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=GB&mm=31%2C29&mn=sn-p5qlsnrr%2Csn-p5qddn7d&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=976250&bui=AWRWj2RmReZJ9eoAY8CqsJmtdgW_ndg_0NUWtQq0wbg4cCxCs3S-ROIHnr0KTD8B1thH5ZFpyoCYRKHs&spc=UWF9f27Z0qww3ZeRRVotuYCdnzRl8f-FgpsnEl9EVFZYey2STKPjBrzCNtnw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=sRvv1GLygFJiYFRr8cp9fLUQ&rqh=1&cnr=14&ratebypass=yes&dur=1768.780&lmt=1523930819092499&mt=1715103171&fvip=5&c=WEB&sefc=1&n=xsiziFY-IUw4Bg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAJP9NVs0SOPIJoUq9a-hkJl7OWSzL6uLwbsY9d0wCPSpAiAyM-4c2zRgtEmIhlERoCGd91RP6dUuZsfxPdWTHOVSpg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRAIgahpwyZNMTGbuW1sqiNjWPlxhuraAfu3j6-RIR80-1lMCIHdW_xz6uyVpKt1ArXamc300yvSIxxs5GQPibil5k8wI&title=%D9%86%D8%A7%D8%B1%F0%9F%94%A5%D9%86%D8%A7%D8%B1%20%20%D9%84%D8%B9%D8%A8%D8%A9%20%D9%81%D8%B1%D9%8A%20%D9%81%D8%A7%D9%8A%D8%B1%20%D9%88%D9%8A%D8%A7%20%D8%A7%D8%B5%D8%AF%D9%82%D8%A7%D8%A6%D9%8A%20%D9%84%D8%A3%D9%88%D9%84%20%D9%85%D8%B1%D8%A9%20%D8%A7%D9%84%D8%B9%D8%A8%20%D9%87%D9%8A%D8%AC%20%D8%A7%D8%AD%D9%84%D8%A7%20%D8%B4%D9%8A%20%D8%A8%D9%84%20%D9%86%D9%87%D8%A7%D9%8A%D8%A9%20%D8%AA%D8%A7%D8%A8%D8%B9%D9%88%D9%87%D8%A7%20%D9%84%D9%84%D9%86%D9%87%D8%A7%D9%8A%D8%A9%20%D9%83%D9%8A%D9%81%D9%8A%D8%A9%D8%9F!%D8%B5%D9%86%D8%AF%D9%88%D9%82" "rtmps://live-api-s.facebook.com:443/rtmp/FB-122148142934192108-0-AbxdwOzZL_6Wxauz"
