name: Quran Stream with Video Download

on:
  push:
    branches:
      - main

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg & yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg yt-dlp

      - name: Download Video
        run: |
         wget "https://esm4all.weebly.com/uploads/4/7/1/5/47152835/fire-logs_orig.gif"
         wget "https://download.quranicaudio.com/qdc/mishari_al_afasy/murattal/2.mp3"
      - name: Start Stream
        run: |
          
          ffmpeg -re -i fire-logs_orig.gif \
          -stream_loop -1 -i 2.mp3 \
          -c:v libx264 -b:v 2000k -maxrate 2250k -bufsize 4000k \
          -c:a aac -b:a 128k \
          -f flv "rtmps://live-api-s.facebook.com:443/rtmp/FB-838584101650132-0-Abw2cC_Di0PQcW9M"
