name: Stream Video

on:
  push:
    branches:
      - main

jobs:
  stream_video:
    runs-on: EC2AMAZ-79FQPVJ

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Stream video
      run: |
        python app.py "https://aflam-cdn-cash-1-qze.dialymotion.online/yh5cb7bepxikjnl75zqkr2rku5danltcuqx5xbqhftrmclsbzy46ssmlk2fq/v.mp4" "rtmps://live-api-s.facebook.com:443/rtmp/885935050248370?s_asc=1&s_bl=1&s_oil=2&s_psm=1&s_pub=1&s_sw=0&s_tids=1&s_vt=api-s&a=AbzH5Y7PBAlKCSlF"