name: Stream Video

on:
  push:
    branches:
      - main

jobs:
  stream_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Stream video
      run: |
        sudo apt install ffmpeg -y
        chmod +x s.sh
        ./s.sh "https://prod-ec-eu-west-3.video.pscp.tv/Transcoding/v1/hls/4pVaTh31CGOejG910k1HHZeK-Ul4lyUxYU92zMZozVcLO6FNA5UVHOLIMoTq_1xnhtSBEGX4Pj6B9PZDVrFPfw/transcode/eu-west-3/periscope-replay-direct-prod-eu-west-3-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJFbmNvZGVyU2V0dGluZyI6ImVuY29kZXJfc2V0dGluZ183MjBwNjBfMTAiLCJIZWlnaHQiOjcyMCwiSGlnaEZyYW1lUmF0ZSI6dHJ1ZSwiS2JwcyI6NDUwMCwiV2lkdGgiOjEyODB9.stuYmPPT9-xV9TCzbYuSxDgDPioKBbwtYnXdCaqBQNo/dynamic_highlatency.m3u8?type=live" "rtmps://edgetee-upload-mad1-1.xx.fbcdn.net:443/rtmp/18412265815064658?s_bl=1&s_fbp=cdg4-1&s_prp=mad1-1&s_spl=1&s_sw=0&s_tids=1&s_vt=ig&a=Abxz8QdJlp8rqhvm
      "
