name: Stream Video

on:
  push:
    branches:
      - main

jobs:
  stream_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Stream video
      run: |
        sudo apt install ffmpeg -y
        chmod +x s.sh
        ./s.sh "https://instagram.ftng2-1.fna.fbcdn.net/hvideo-prn/_nc_cat-105/v/rASeuoHMVIJXT9r_pcfHgqMuw5OqHueAnZXO5hqSVNggcqw/_nc_ohc-I2jA7n6mAo0Q7kNvgFxD7vf/live-dash/dash-abr/18412265815064658.mpd?ccb=2-4&ms=m_CN&oh=00_AYDz9vosIzQd44FaZuzByb15QvMYMSXxZhhtzFliQxhFlg&oe=66417A9F" "rtmps://live-api-s.facebook.com:443/rtmp/FB-122149281380192108-0-AbxN7gHANOlGtKc7"
