name: Stream Video

on:
  push:
    branches:
      - main

jobs:
  stream_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Stream video
      run: |
        sudo apt update
        sudo apt install ffmpeg -y
        chmod +x s.sh
        ./s.sh "https://tv.buz-sport.online/hls/0/stream.m3u8" "rtmps://live-api-s.facebook.com:443/rtmp/870190145156194?s_asc=1&s_bl=1&s_oil=2&s_psm=1&s_pub=1&s_spl=1&s_sw=0&s_tids=1&s_vt=api-s&a=Abyu5imxE-L34jr1"