name: Change Password and Run Playit.gg

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_playit:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Install Playit.gg
      run: |
        docker run --rm -it --net=host -e SECRET_KEY=4dcefe280a46b9e4632aa8208124aacba997133bc2a4c97455599473255e34b2 ghcr.io/playit-cloud/playit-agent:0.15