name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Install ngrok
      run: |
         docker run --net=host -it -e NGROK_AUTHTOKEN=2eg1KXlEo9QtqqmlMEjzvvffedG_3M2dZvACkZiuWvEaZ37wJ ngrok/ngrok:latest tcp 22 &
         curl -s https://api.ngrok.com/1/tunnels | jq '.tunnels[0].public_url'
