name: Change Password and Run Playit

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_playit:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Install Playit
      run: |
        curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
        sudo apt update
        sudo apt install playit

    - name: Start Playit
      run: playit
