name: Setup Ubuntu Desktop and RDP

on: [push]

jobs:
  setup-desktop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update APT and install tasksel
      run: |
        sudo apt-get update
        sudo apt-get install -y tasksel
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)
    - name: Install Ubuntu Desktop
      run: |
        sudo tasksel install ubuntu-desktop

    - name: Install and configure XRDP
      run: |
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo adduser xrdp ssl-cert

    - name: Open RDP port 3389
      run: |
        sudo apt-get install -y ufw
        sudo ufw allow 3389

    - name: Install SSH client
      run: |
        sudo apt-get install -y openssh-client

    - name: Forward RDP port using Serveo.net
      run: |
        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -R 0:localhost:3389 serveo.net
